### ISSUE TITLE
Why do you use Evcache ?

### ISSUE THREAD

**Issue by HelloTo4x** [mgnsk/evcache#33]
Hi, why you use Evcache for caching instead of other caches like Ehcache or Redis, what are diffrence between them

**Comment by mgnsk** [comment]
We use evcache in production mostly for caching small results like DNS and database queries. Compared to other caching solutions, it has no external dependencies outside of the go standard library and the main feature that makes it suitable is the key-granular locking `Fetch` which acts as a deduplicator.

Here's an example of a caching lookup. If multiple goroutines concurrently resolve the same host, then only a single lookup request is made and everybody gets the cached result.

```go
type CachedResolver struct {
	cache    *evcache.Cache
	resolver *net.Resolver
}

func (r *CachedResolver) LookupHost(ctx context.Context, host string) (addrs []string, err error) {
	result, c, err := r.cache.Fetch(host, time.Minute, func() (interface{}, error) {
                // Do an expensive query or lookup here.
		return r.resolver.LookupHost(ctx, host)
	})
	if err != nil {
		return nil, err
	}

	defer c.Close()

	return result.([]string), nil
}
```

**Comment by HelloTo4x** [comment]
u mean to avoid Duplicating data, and i see Redis can do it, and it also has library to connect to Golang
